services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: installment_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DATABASE_URL: postgres://postgres:1234@db:5432/installment_db  # ใช้ชื่อ service db แทน localhost
    depends_on:
      - db
    volumes:
      - ./backend:/app
    command: npm run dev

volumes:
  pgdata:
