services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: installment_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .                     # 🟢 ใช้ root เป็น context เพื่อเข้าถึง frontend ได้
      dockerfile: backend/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    # environment:
    #   PORT: PORT=3000
    #   DATABASE_URL: postgres://postgres:1234@db:5432/installment_db
    depends_on:
      - db
    volumes:
      - ./backend:/app                # ⬅️ mount backend code
      - ./frontend:/app/frontend      # ⬅️ mount frontend code เข้า container
    command: npm run dev

volumes:
  pgdata:
