services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .  # ใช้ root context เพื่อเข้าถึงทั้ง backend และ frontend
      dockerfile: backend/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - ./frontend:/app/frontend
    command: npm run dev

volumes:
  pgdata:
